using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using Chirp.CSVDB;
using Chirp.General;
using JetBrains.Annotations;
using Microsoft.Data.Sqlite;
using Xunit;

namespace Chirp.DBFacade.Tests;

[TestSubject(typeof(DBFacade<>))]
// We *want* to test against the interface, so this IDE warning is ignored.
[SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance")]
public class DBFacadeTest {
    [Fact]
    public void CanGetInstance() {
        IDataBaseRepository<Cheep> database = DBFacade<Cheep>.Instance;
        Assert.NotNull(database);
    }

    [Theory]
    [InlineData(null, 657)]
    [InlineData(1, 1)]
    [InlineData(2, 2)]
    [InlineData(3, 3)]
    [InlineData(0, 0)]
    [InlineData(800, 657)]
    public void Read(int? limit, int expectedCount) {
        IDataBaseRepository<Cheep> database = DBFacade<Cheep>.Instance;
        IEnumerable<Cheep> results = database.Read(limit);
        Assert.NotNull(results);
        Assert.Equal(expectedCount, results.ToList().Count);
    }

    [Theory]
    [InlineData(-1)]
    [InlineData(-2)]
    public void ReadNegative(int limit) {
        Assert.Throws<ArgumentOutOfRangeException>(() => DBFacade<Cheep>.Instance.Read(limit));
    }

    [Fact]
    public void StoreSpaceInName() {
        IDataBaseRepository<Cheep> database = DBFacade<Cheep>.Instance;
        database.Store(new Cheep("Wendell Ballan", "This should be fine!", 123535467));
    }

    [Fact]
    public void StoreApostropheSingle() {
        IDataBaseRepository<Cheep> database = DBFacade<Cheep>.Instance;
        database.Store(new Cheep("Wendell Ballan",
            "Am I the only one whose message wasn't computer-generated by some website?!",
            1758918796));
    }

    [Fact]
    public void StoreNonExistentUsername() {
        IDataBaseRepository<Cheep> database = DBFacade<Cheep>.Instance;
        Assert.Throws<SqliteException>(() => 
            database.Store(new Cheep("adgrardgaed",
                "I have no user-name, and I must scream",
                1758919010)));
    }
}